### ISSUE TITLE
Tombstone bundles for failed 10x Integration Test projects in prod

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-store#2285]
project_uuid=bf0a4797-76fa-4856-af05-42075ee89bc1
Project Label    prod/optimus/2019-07-22T15:23:12Z

**Comment by xbrianh** [comment]
Done.

**Comment by theathorn** [comment]
It's still showing up in the Azul index and Data Browser:
project_uuid=bf0a4797-76fa-4856-af05-42075ee89bc1

Also, there's now now an additional failed 10x Integration Test:
project_uuid=8eede5c4-0c36-423d-802e-69b35b279f3e project_label=prod/optimus/2019-07-25T12:02:06Z

**Comment by theathorn** [comment]
@hannes-ucsc Can you confirm both projects are still in the Data Store and therefore the Azul index correctly reflects reality?

**Comment by xbrianh** [comment]
@theathorn I've double checked and this project UUID does not appear in the DSS index, so I'm closing this ticket for now.

Future dcp-wide integration test bundles should be cleaned up via the CI/CD facilitated framework under development [here](https://github.com/HumanCellAtlas/dcp/pull/462).

**Comment by theathorn** [comment]
Both projects still appear in the Data Browser.

@hannes-ucsc wrote:

They forgot to delete the analysis bundles. Those are still present in the DSS:
(.venv) eduroam-169-233-135-217:azul hannes$ http 'https://service.explore.data.humancellatlas.org/repository/bundles?filters={"projectId":{"is":["bf0a4797-76fa-4856-af05-42075ee89bc1","8eede5c4-0c36-423d-802e-69b35b279f3e"]}}&size=15' | jq '.hits[]|{bundle: .bundles[0].bundleUuid, version: .bundles[0].bundleVersion, project: .projects[0].projectShortname[0]}'
{
  "bundle": "70f56827-1148-4444-ac74-ce803f20be01",
  "version": "2019-07-25T145142.955732Z",
  "project": "prod/optimus/2019-07-25T12:02:06Z"
}
{
  "bundle": "2fc3048c-77b6-4fce-8649-0e10d8cf6184",
  "version": "2019-07-25T120417.973958Z",
  "project": "prod/optimus/2019-07-25T12:02:06Z"
}
{
  "bundle": "9fda2d99-4f16-4476-a5e7-ad17318b0806",
  "version": "2019-07-23T012100.111357Z",
  "project": "prod/optimus/2019-07-22T15:23:12Z"
}
(.venv) eduroam-169-233-135-217:azul hannes$ http HEAD 'https://dss.data.humancellatlas.org/v1/bundles/70f56827-1148-4444-ac74-ce803f20be01?version=2019-07-25T145142.955732Z&replica=aws'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 58796
Content-Type: application/json
Date: Tue, 30 Jul 2019 22:09:07 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-AWS-REQUEST-ID: 21fd7936-58e0-42a1-997e-590f786dac10
X-Amzn-Trace-Id: Root=1-5d40c003-669d01ac63d8842493c3a468;Sampled=0
x-amz-apigw-id: dqLwnEvBoAMFSNw=
x-amzn-Remapped-Content-Length: 58796
x-amzn-RequestId: a6b73e9b-b316-11e9-98ee-8935cd92abfb



(.venv) eduroam-169-233-135-217:azul hannes$ http HEAD 'https://dss.data.humancellatlas.org/v1/bundles/2fc3048c-77b6-4fce-8649-0e10d8cf6184?version=2019-07-25T120417.973958Z&replica=aws'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 9937
Content-Type: application/json
Date: Tue, 30 Jul 2019 22:09:32 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-AWS-REQUEST-ID: 746cc9f7-7371-41ff-a281-fb9aa679a577
X-Amzn-Trace-Id: Root=1-5d40c01c-abbbee9e5dd2a2f8d95d5690;Sampled=0
x-amz-apigw-id: dqL0aEiiIAMFSjQ=
x-amzn-Remapped-Content-Length: 9937
x-amzn-RequestId: b5334891-b316-11e9-8463-a58521f32529



(.venv) eduroam-169-233-135-217:azul hannes$ http HEAD 'https://dss.data.humancellatlas.org/v1/bundles/9fda2d99-4f16-4476-a5e7-ad17318b0806?version=2019-07-23T012100.111357Z&replica=aws'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 58796
Content-Type: application/json
Date: Tue, 30 Jul 2019 22:09:58 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-AWS-REQUEST-ID: 3112425e-a602-444f-ab2e-5e1e931d1c89
X-Amzn-Trace-Id: Root=1-5d40c036-0da9b3225a65e86467855df0;Sampled=0
x-amz-apigw-id: dqL4eHSwoAMFaiQ=
x-amzn-Remapped-Content-Length: 58796
x-amzn-RequestId: c4b046d6-b316-11e9-98ee-e99f1c415e8c

**Comment by xbrianh** [comment]
@theathorn Thank you for the extra information. This should now be complete.
